name: fruta_no_pe
description: Aplicativo de mapeamento de árvores frutíferas

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  open_route_service: ^1.2.2
  latlong2: ^0.9.0
  provider: ^6.0.5
  json_annotation: ^4.8.1
  geojson_vi: ^2.0.1
  proj4dart: ^2.1.0
  geolocator: ^14.0.0
  flutter_map_cancellable_tile_provider: ^3.1.0
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/arvore.geojson